### ISSUE TITLE
Eliminar líneas de código.

### ISSUE THREAD

**Issue by OscarTalero** [gasiferox/G40-Cycle4-DAW-ClassExercises#1]
Puedes eliminar la linea 13:
const {createReadStream} = require('fs');

y modificar la linea 23 adicionando 'fs':
fs.createReadStream('Clase_5/clase5.html').pipe(res);

el metodo createReadStream() esta incluido en el modulo fs.

**Comment by gasiferox** [comment]
@OscarTalero muchas gracias por tu contribución, ya quedó implementada.  Queda muy claro que el método `createReadStream()` hace parte del módulo `fs`
